spring:
  application:
    name: user-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: priya
#    password: 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: userdb

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082



